import DEAL_IMG from '../assets/sign_doc.jpg';

export const INVESTOR_TYPE = [
    {
        id: 1,
        key: 'business_angle',
        value: "Business Angel (investing my own capital into startups' equity)",
    },
    {
        id: 2,
        key: 'corporate_vc',
        value: 'Corporate VC - General Partner or Managing Partner or Partner (investing corporate capital)',
    },
    {
        id: 3,
        key: 'crypto_fund',
        value: 'Crypto Fund - General Partner or Managing Partner or Partner (investing LP capital)',
    },
    {
        id: 4,
        key: 'family_office',
        value: 'Family Office Investment Manager (investing FO capital)',
    },
    {
        id: 5,
        key: 'hedge_fund',
        value: 'Hedge Fund - General Partner or Managing Partner or Partner (investing LP capital)',
    },
    {
        id: 6,
        key: 'institutional_investor',
        value: 'Institutional Investor - Investment Manager',
    },
    {
        id: 7,
        key: 'limited_partner',
        value: 'Limited partner (investing my own capital into funds)',
    },
    {
        id: 8,
        key: 'sovereign_wealth',
        value: 'Sovereign Wealth - Investment Manager',
    },
    {
        id: 9,
        key: 'sponsor',
        value: 'Sponsor (company interested to offer services to investors or their portfolio companies)',
    },
    {
        id: 10,
        key: 'vc_fund',
        value: 'VC Fund - General partner or Managing Partner or Partner (investing LP capital)',
    },
];

export const INVESTMENT_SECTORS = [
    'Advertising',
    'AgTech',
    'AI',
    'Analytics',
    'AR/VR',
    'AudioTech',
    'AutoTech',
    'BioTech',
    'Bockchain / Crypto / Web3',
    'ClimateTech / CealTech',
    'Cloud Computing',
    'Cloud Infrastructure',
    'ConstructioinTech',
    'Consumer Health',
    'Consumer Internet',
    'Cosmetics',
    'Creator Economy',
    'Cyber Security',
    'D2C',
    'Data Services',
    'DeepTech',
    'Developer Tools',
    'Diagnostics',
    'Digital Health',
    'Drug Delivery',
    'E-Commerce',
    'EdTech',
    'EnergyTech',
    'Enterprise',
    'Entertainment & Sports',
    'ESG',
    'FashionTech',
    'FinTech',
    'FoodTech',
    'Feature of Work',
    'Games',
    'Gaming/eSports',
    'Generative Tech',
    'Gig Economy',
    'GovTech',
    'Hardware',
    'HealthTech',
    'Hospitality / Lodging',
    'HRTech / Human Capital',
    'Impact',
    'insurTech',
    'IoT',
    'LegalTech',
    'Local Services',
    'Logistics',
    'Manufacturing',
    'MarketignTech',
    'Marketplaces',
    'Material Science',
    'medical Devices',
    'Mobility',
    'Other',
    'Paas',
    'Parenting & Families',
    'Payments',
    'Pharmaceuticals',
    'Real Estate/Prop Tech',
    'Retail',
    'Robotics',
    'SaaS',
    'Sales & CRM',
    'Security',
    'Semiconductors',
    'Smart Cities / Urban Tech',
    'SMB',
    'Social Commerce',
    'Social Networks',
    'SpaceTech',
    'Supply Chain Tech',
    'Therapecutics',
    'TransportationTech',
    'Travel',
    'VC Funds',
    'Wellness & Fitness',
];

export const DEAL_SIZE = ['0', '1-5', '5-10', '10-15', '15-20', '20-30', '30-40', '50+'];

export const INVESTMENT_SIZE = [
    '0-$10K',
    '$10k-$25K',
    '$25K-$50K',
    '$50K-$100K',
    '$100K-$500K',
    '$500K-$1M',
    '$1M-$5M',
    '$5M+',
];

export const INVESTMENT_STAGES = [
    'Pre-Seed',
    'Seed',
    'Seed Extension',
    'Series A',
    'Series B',
    'Series C',
    'Series D',
    'Series E',
    'Series F',
    'Series H+',
    'Token Sale (SAFT)',
    'Token Sale',
    'Secondary Equity',
    'Secondary SAFT',
    'VC Fund',
    'Other',
];

export const GEOGRAPHIES = [
    'North America',
    'Europe',
    'Israel',
    'MENA',
    'LATAM',
    'Africa',
    'India',
    'South East Asia',
    'China',
    'Centeral Asia',
    'Australia',
];

export const DEALS = [
    {
        id: 1,
        type: 'date',
        date: '2023-10-20',
    },
    {
        id: 2,
        type: 'data',
        data: {
            attribute: [
                'AR/VR',
                'Medicine',
                'Shopping',
                'AR/VR',
                'Medicine',
                'Shopping',
                'AR/VR',
                'Medicine',
                'Shopping',
            ],
            name: 'Popular Brands',
            summary: 'This is John Bill who want to make an investment. Thanks',
            investmentType: 'Series A',
            investmentSize: '$10K-$25K',
            ownerName: 'James William',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 3,
        type: 'data',
        data: {
            attribute: ['Space', 'Medicine', 'Shopping'],
            name: 'Artificial Satellites',
            summary: 'This is Bot Nazim who want to make an investment. Thanks',
            investmentType: 'Series E',
            investmentSize: '$10K-$25K',
            ownerName: 'Mac Yoske',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 4,
        type: 'data',
        data: {
            attribute: ['Blockchain / Crypto', 'Medicine', 'Shopping', 'Space'],
            name: 'Bitcoin Investment',
            summary: 'This is Pull Kim who want to make an investment. Thanks',
            investmentType: 'Pree-Seed',
            investmentSize: '$5M+',
            ownerName: 'Wang Chan',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 5,
        type: 'data',
        data: {
            attribute: ['Medicine', 'Equipments'],
            name: 'Medicine Investment',
            summary: 'This is Huss Verkati who want to make an investment. Thanks',
            investmentType: 'Seed Extension',
            investmentSize: '$100K-$500K',
            ownerName: 'Mr. Jone',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 6,
        type: 'data',
        data: {
            attribute: ['Car', 'AR/VR', 'AI'],
            name: 'Motor World',
            summary: 'This is Diana Vem who want to make an investment. Thanks',
            investmentType: 'Token Sale',
            investmentSize: '$1M-$5M',
            ownerName: 'James William',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 7,
        type: 'date',
        date: '2023-10-22',
    },
    {
        id: 8,
        type: 'data',
        data: {
            attribute: ['AR/VR'],
            name: 'VR Investor',
            summary: 'This is John Bill who want to make an investment. Thanks',
            investmentType: 'Series A',
            investmentSize: '$10K-$25K',
            ownerName: 'James William',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 9,
        type: 'data',
        data: {
            attribute: ['Space', 'AI'],
            name: 'Space like SpaceX',
            summary: 'This is Bot Nazim who want to make an investment. Thanks',
            investmentType: 'Series E',
            investmentSize: '$10K-$25K',
            ownerName: 'Mac Yoske',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 10,
        type: 'data',
        data: {
            attribute: ['Blockchain / Crypto'],
            name: 'Crypto Development',
            summary: 'This is Pull Kim who want to make an investment. Thanks',
            investmentType: 'Pree-Seed',
            investmentSize: '$5M+',
            ownerName: 'Wang Chan',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 11,
        type: 'data',
        data: {
            attribute: ['Medicine'],
            name: 'Equipment developing',
            summary: 'This is Huss Verkati who want to make an investment. Thanks',
            investmentType: 'Seed Extension',
            investmentSize: '$100K-$500K',
            ownerName: 'Mr. Jone',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
    {
        id: 12,
        type: 'data',
        data: {
            attribute: ['Car'],
            name: 'Work with Tesla',
            summary: 'This is Diana Vem who want to make an investment. Thanks',
            investmentType: 'Token Sale',
            investmentSize: '$1M-$5M',
            ownerName: 'James William',
            primaryContact: '+1-2018971232',
            address: 'Harlem, Manhattan, New York, NY',
            attachments: {
                executiveSummery: 'https://example.com/executive-summery',
                projection: 'https://example.com/projection',
                misc: 'https://example.com/misc',
            },
            img: DEAL_IMG,
        },
    },
];
